{!! file_get_contents(base_path('docs/api-references/api.md')) !!}
{!! file_get_contents(base_path('docs/api-references/category.md')) !!}
{!! file_get_contents(base_path('docs/api-references/product.md')) !!}
{!! file_get_contents(base_path('docs/api-references/detail_product.md')) !!}
{!! file_get_contents(base_path('docs/api-references/post.md')) !!}
{!! file_get_contents(base_path('docs/api-references/comment.md')) !!}
{!! file_get_contents(base_path('docs/api-references/order.md')) !!}
{!! file_get_contents(base_path('docs/api-references/user.md')) !!}
{!! file_get_contents(base_path('docs/api-references/profile.md')) !!}
{!! file_get_contents(base_path('docs/api-references/detail_order.md')) !!}
{!! file_get_contents(base_path('docs/api-references/resetpass.md')) !!}